    
    alter session set "_oracle_script"=true;
    --Database creation
    create user DB identified by FAHMENIAC;
    GRANT ALL PRIVILEGES TO DB;

    alter session set "_oracle_script"=true;
    --Data Warehouse creation
    create user DBW identified by FAHMENIAC;
    GRANT ALL PRIVILEGES TO DBW;
    
    --------------------------------------------------------
--  DDL for Table CUST_FACT
--------------------------------------------------------

  CREATE TABLE "DBW"."CUST_FACT" 
   (	"CUSTOMER_ID" NUMBER, 
	"ACCT_ID" CHAR(14 BYTE), 
	"ACCT_TYPE" CHAR(1 BYTE), 
	"BANK_ID" CHAR(4 BYTE), 
	"BRANCH_ID" CHAR(4 BYTE), 
	"TRAN_ID" NUMBER(*,0), 
	"BALANCE" NUMBER(14,2), 
	"TRAN_DATETIME" DATE DEFAULT SYSDATE, 
	"TRAN_TYPE" CHAR(1 BYTE), 
	"TRAN_AMOUNT" NUMBER(14,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUST_FACT
--------------------------------------------------------

  ALTER TABLE "DBW"."CUST_FACT" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "DBW"."CUST_FACT" MODIFY ("ACCT_ID" NOT NULL ENABLE);
  ALTER TABLE "DBW"."CUST_FACT" MODIFY ("ACCT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DBW"."CUST_FACT" MODIFY ("BANK_ID" NOT NULL ENABLE);
  ALTER TABLE "DBW"."CUST_FACT" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
  ALTER TABLE "DBW"."CUST_FACT" MODIFY ("TRAN_ID" NOT NULL ENABLE);
  ALTER TABLE "DBW"."CUST_FACT" MODIFY ("BALANCE" NOT NULL ENABLE);
  ALTER TABLE "DBW"."CUST_FACT" MODIFY ("TRAN_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DBW"."CUST_FACT" MODIFY ("TRAN_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DBW"."CUST_FACT" MODIFY ("TRAN_AMOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CUST_FACT
--------------------------------------------------------

  ALTER TABLE "DBW"."CUST_FACT" ADD CONSTRAINT "CUST_FACT_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "DBW"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "DBW"."CUST_FACT" ADD CONSTRAINT "BANK_FACT_FK" FOREIGN KEY ("BANK_ID")
	  REFERENCES "DBW"."BANK_MST" ("BANK_ID") ENABLE;
  ALTER TABLE "DBW"."CUST_FACT" ADD CONSTRAINT "ACCT_TYPE_FFK" FOREIGN KEY ("ACCT_TYPE")
	  REFERENCES "DBW"."ACCOUNT_TYPE" ("ACCT_TYPE") ENABLE;
  ALTER TABLE "DBW"."CUST_FACT" ADD CONSTRAINT "BRANCH_FFK" FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "DBW"."BRANCH_MST" ("BRANCH_ID") ENABLE;
  ALTER TABLE "DBW"."CUST_FACT" ADD CONSTRAINT "TRAN_FFK" FOREIGN KEY ("TRAN_ID")
	  REFERENCES "DBW"."TRANSACTION" ("TRAN_ID") ENABLE;
  ALTER TABLE "DBW"."CUST_FACT" ADD CONSTRAINT "TRAN_TYPE_FFK" FOREIGN KEY ("TRAN_TYPE")
	  REFERENCES "DBW"."TRANSACTION_TYPE" ("TRAN_TYPE") ENABLE;
  ALTER TABLE "DBW"."CUST_FACT" ADD CONSTRAINT "ACCT_FFK" FOREIGN KEY ("ACCT_ID")
	  REFERENCES "DBW"."ACCOUNT" ("ACCT_ID") ENABLE;
