--------------------------------------------------------
--  DDL for Table CREDENTIALS
--------------------------------------------------------

  CREATE TABLE "CREDENTIALS" 
   (	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"LAST_LOGIN" DATE DEFAULT SYSDATE, 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table TRANSACTION_TYPE
--------------------------------------------------------

  CREATE TABLE "TRANSACTION_TYPE" 
   (	"TRAN_TYPE" CHAR(1 BYTE), 
	"DESCRIPTION" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRANSACTION_TYPE_PK" ON "TRANSACTION_TYPE" ("TRAN_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRANSACTION_TYPE
--------------------------------------------------------

  ALTER TABLE "TRANSACTION_TYPE" MODIFY ("TRAN_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION_TYPE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION_TYPE" ADD CONSTRAINT "TRANSACTION_TYPE_PK" PRIMARY KEY ("TRAN_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  DDL for Table ACC_TYPE_MST
--------------------------------------------------------

  CREATE TABLE "ACC_TYPE_MST" 
   (	"ACCT_TYPE" CHAR(1 BYTE), 
	"DESCRIPTION" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACC_TYPE_MST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACC_TYPE_MST_PK" ON "ACC_TYPE_MST" ("ACCT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACC_TYPE_MST
--------------------------------------------------------

  ALTER TABLE "ACC_TYPE_MST" ADD CONSTRAINT "ACC_TYPE_MST_PK" PRIMARY KEY ("ACCT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ACC_TYPE_MST" MODIFY ("ACCT_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "ACC_TYPE_MST" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  DDL for Table BRANCH_MST
--------------------------------------------------------

  CREATE TABLE "BRANCH_MST" 
   (	"BRANCH_ID" CHAR(4 BYTE), 
	"BANK_ID" CHAR(4 BYTE), 
	"BRANCH_NM" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PROVINCE" VARCHAR2(20 BYTE), 
	"POSTAL" VARCHAR2(6 BYTE), 
	"CONTACT_NO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BRANCH_MST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BRANCH_MST_PK" ON "BRANCH_MST" ("BRANCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BRANCH_MST
--------------------------------------------------------

  ALTER TABLE "BRANCH_MST" ADD CONSTRAINT "BRANCH_MST_PK" PRIMARY KEY ("BRANCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BRANCH_MST" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH_MST" MODIFY ("BANK_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH_MST" MODIFY ("BRANCH_NM" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH_MST" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH_MST" MODIFY ("CITY" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH_MST" MODIFY ("PROVINCE" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH_MST" MODIFY ("POSTAL" NOT NULL ENABLE);
 
  ALTER TABLE "BRANCH_MST" MODIFY ("CONTACT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BRANCH_MST
--------------------------------------------------------

  ALTER TABLE "BRANCH_MST" ADD CONSTRAINT "BANK_FK" FOREIGN KEY ("BANK_ID")
	  REFERENCES "BANK_MST" ("BANK_ID") ENABLE;


--------------------------------------------------------
--  DDL for Table BANK_MST
--------------------------------------------------------

  CREATE TABLE "BANK_MST" 
   (	"BANK_ID" CHAR(4 BYTE), 
	"BANK_NM" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BANK_MST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BANK_MST_PK" ON "BANK_MST" ("BANK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BANK_MST
--------------------------------------------------------

  ALTER TABLE "BANK_MST" ADD CONSTRAINT "BANK_MST_PK" PRIMARY KEY ("BANK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BANK_MST" MODIFY ("BANK_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BANK_MST" MODIFY ("BANK_NM" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table CUSTOMER_MST
--------------------------------------------------------

  CREATE TABLE "CUSTOMER_MST" 
   (	"CUSTOMER_ID" NUMBER, 
	"BANK_ID" CHAR(4 BYTE), 
	"BRANCH_ID" CHAR(4 BYTE), 
	"CUSTOMER_NM" VARCHAR2(30 BYTE), 
	"CONTACT_NO" NUMBER(10,0), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"BIRTHDATE" DATE, 
	"GENDER" CHAR(10 BYTE), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PROVINCE" VARCHAR2(20 BYTE), 
	"POSTAL" VARCHAR2(6 BYTE), 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_MST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUSTOMER_MST_PK" ON "CUSTOMER_MST" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER_MST
--------------------------------------------------------

  ALTER TABLE "CUSTOMER_MST" ADD CONSTRAINT "CUSTOMER_MST_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("BANK_ID" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("BRANCH_ID" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("CUSTOMER_NM" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("CONTACT_NO" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("BIRTHDATE" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("CITY" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("PROVINCE" NOT NULL ENABLE);
 
  ALTER TABLE "CUSTOMER_MST" MODIFY ("POSTAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER_MST
--------------------------------------------------------

  ALTER TABLE "CUSTOMER_MST" ADD CONSTRAINT "BANK_MST_FK" FOREIGN KEY ("BANK_ID")
	  REFERENCES "BANK_MST" ("BANK_ID") ENABLE;
 
  ALTER TABLE "CUSTOMER_MST" ADD CONSTRAINT "BRANCH_MST_FK" FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "BRANCH_MST" ("BRANCH_ID") ENABLE;

  --------------------------------------------------------
--  DDL for Table ACCOUNT_MST
--------------------------------------------------------

  CREATE TABLE "ACCOUNT_MST" 
   (	"ACCT_ID" CHAR(14 BYTE), 
	"OPEN_DATE" DATE, 
	"CUSTOMER_ID" NUMBER, 
	"ACCT_TYPE" CHAR(1 BYTE), 
	"STATUS" CHAR(10 BYTE), 
	"CLOSE_DT" DATE, 
	"BALANCE" NUMBER(14,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCOUNT_MST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACCOUNT_MST_PK" ON "ACCOUNT_MST" ("ACCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNT_MST
--------------------------------------------------------

  ALTER TABLE "ACCOUNT_MST" ADD CONSTRAINT "ACCOUNT_MST_PK" PRIMARY KEY ("ACCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ACCOUNT_MST" MODIFY ("ACCT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ACCOUNT_MST" MODIFY ("OPEN_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ACCOUNT_MST" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ACCOUNT_MST" MODIFY ("ACCT_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "ACCOUNT_MST" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "ACCOUNT_MST" MODIFY ("BALANCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT_MST
--------------------------------------------------------

  ALTER TABLE "ACCOUNT_MST" ADD CONSTRAINT "ACCT1_FK" FOREIGN KEY ("ACCT_TYPE")
	  REFERENCES "ACC_TYPE_MST" ("ACCT_TYPE") ENABLE;
 
  ALTER TABLE "ACCOUNT_MST" ADD CONSTRAINT "CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER_MST" ("CUSTOMER_ID") ENABLE;

--------------------------------------------------------
--  DDL for Table BENEFICIARY_MST
--------------------------------------------------------

  CREATE TABLE "BENEFICIARY_MST" 
   (	"BENEF_ID" NUMBER, 
	"BENEF_NM" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'Y', 
	"DELETE_DATE" DATE, 
	"ACCT_ID" CHAR(14 BYTE), 
	"CUSTOMER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BENEFICIARY_MST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BENEFICIARY_MST_PK" ON "BENEFICIARY_MST" ("BENEF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger BENEFICIARY_MST_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BENEFICIARY_MST_TRG" 
BEFORE INSERT ON BENEFICIARY_MST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.BENEF_ID IS NULL THEN
      SELECT BENEFICIARY_MST_SEQ.NEXTVAL INTO :NEW.BENEF_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BENEFICIARY_MST_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table BENEFICIARY_MST
--------------------------------------------------------

  ALTER TABLE "BENEFICIARY_MST" ADD CONSTRAINT "BENEFICIARY_MST_PK" PRIMARY KEY ("BENEF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "BENEFICIARY_MST" MODIFY ("BENEF_ID" NOT NULL ENABLE);
 
  ALTER TABLE "BENEFICIARY_MST" MODIFY ("BENEF_NM" NOT NULL ENABLE);
 
  ALTER TABLE "BENEFICIARY_MST" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "BENEFICIARY_MST" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "BENEFICIARY_MST" MODIFY ("STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "BENEFICIARY_MST" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "TRANSACTION" 
   (	"TRAN_ID" NUMBER(*,0), 
	"TRAN_DT" DATE DEFAULT SYSDATE, 
	"ACCT_ID" CHAR(14 BYTE), 
	"TRAN_TYPE" CHAR(1 BYTE), 
	"TRAN_AMOUNT" NUMBER(14,2), 
	"BENEF_ID" NUMBER, 
	"TOTAL_AMT" NUMBER(14,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRANSACTION_PK" ON "TRANSACTION" ("TRAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_INDEX1
--------------------------------------------------------

  CREATE INDEX "TRANSACTION_INDEX1" ON "TRANSACTION" ("BENEF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_INDEX2
--------------------------------------------------------

  CREATE INDEX "TRANSACTION_INDEX2" ON "TRANSACTION" ("ACCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_INDEX3
--------------------------------------------------------

  CREATE INDEX "TRANSACTION_INDEX3" ON "TRANSACTION" ("TRAN_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIG_UPDATE_BALANCE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRIG_UPDATE_BALANCE" 
BEFORE DELETE OR INSERT ON TRANSACTION 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
DECLARE
A_BALANCE ACCOUNT_MST.BALANCE%TYPE;
BEGIN

  IF INSERTING THEN 
        BEGIN
            SELECT A.BALANCE INTO A_BALANCE
            FROM ACCOUNT_MST A
            WHERE A.ACCT_ID = :NEW.ACCT_ID;
        EXCEPTION WHEN NO_DATA_FOUND THEN 
            A_BALANCE := 0;
        END;
        A_BALANCE := A_BALANCE + (CASE WHEN :NEW.TRAN_TYPE = 'D' THEN :NEW.TRAN_AMOUNT ELSE (-1)*(:NEW.TRAN_AMOUNT) END);
        :NEW.TOTAL_AMT:= A_BALANCE;

        BEGIN 
            UPDATE ACCOUNT_MST A
            SET A.BALANCE = A_BALANCE 
            WHERE A.ACCT_ID = :NEW.ACCT_ID;
        EXCEPTION WHEN NO_DATA_FOUND THEN 
            NULL;
        END; 

    ELSIF DELETING THEN 
        BEGIN
            SELECT A.BALANCE INTO A_BALANCE
            FROM ACCOUNT_MST A
            WHERE A.ACCT_ID = :OLD.ACCT_ID;
        EXCEPTION WHEN NO_DATA_FOUND THEN 
            A_BALANCE := 0;
        END;
        A_BALANCE := A_BALANCE - (CASE WHEN :OLD.TRAN_TYPE = 'D' THEN :OLD.TRAN_AMOUNT ELSE (-1)*(:OLD.TRAN_AMOUNT) END);
        BEGIN 
            UPDATE ACCOUNT_MST A
            SET A.BALANCE = A_BALANCE 
            WHERE A.ACCT_ID = :OLD.ACCT_ID;
        EXCEPTION WHEN NO_DATA_FOUND THEN 
            NULL;
        END;
    END IF;


END;
/
ALTER TRIGGER "TRIG_UPDATE_BALANCE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRANSACTION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRANSACTION_TRG" 
BEFORE INSERT ON TRANSACTION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TRANSACTION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRANSACTION_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRANSACTION_TRG1" 
BEFORE INSERT ON TRANSACTION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TRAN_ID IS NULL THEN
      SELECT TRANSACTION_SEQ1.NEXTVAL INTO :NEW.TRAN_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TRANSACTION_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TRANSACTION" MODIFY ("TRAN_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("TRAN_DT" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("ACCT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("TRAN_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("TRAN_AMOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" MODIFY ("TOTAL_AMT" NOT NULL ENABLE);
 
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("TRAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "ACCT_FK" FOREIGN KEY ("ACCT_ID")
	  REFERENCES "ACCOUNT_MST" ("ACCT_ID") ENABLE;
 
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "BENEF_FK" FOREIGN KEY ("BENEF_ID")
	  REFERENCES "BENEFICIARY_MST" ("BENEF_ID") ENABLE;
 
  ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRAN_TYPE_FK" FOREIGN KEY ("TRAN_TYPE")
	  REFERENCES "TRANSACTION_TYPE" ("TRAN_TYPE") ENABLE;

