
CREATE TABLE "CUSTOMER"
    (   "CUSTOMER_ID" NUMBER NOT NULL ENABLE,
    "CUSTOMER_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE,
    CITY VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PROVINCE VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "CUSTOMER_ID_PK" PRIMARY KEY("CUSTOMER_ID"));
    
    CREATE TABLE "ACCOUNT"
    (  
    ACCT_ID CHAR(14 BYTE) NOT NULL ENABLE,
    "CUSTOMER_ID" NUMBER NOT NULL ENABLE,
    "ACCT_TYPE" CHAR(1 BYTE) NOT NULL ENABLE,
    "BALANCE" NUMBER(14, 2) NOT NULL ENABLE,
    "STATUS" CHAR(10 BYTE) NOT NULL ENABLE,
    "OPEN_DATE" DATE,
	 CONSTRAINT "ACCT_PK" PRIMARY KEY ("ACCT_ID"));
    
    CREATE TABLE "ACCOUNT_TYPE"
    (   "ACCT_TYPE" CHAR(1 BYTE) NOT NULL ENABLE,
    "DESCRIPTION" VARCHAR(25 BYTE) NOT NULL ENABLE,
    CONSTRAINT "ACCT_TYPE_PK" PRIMARY KEY  ("ACCT_TYPE"));
    
    CREATE TABLE "BANK_MST" 
   (	"BANK_ID" CHAR(4 BYTE) NOT NULL ENABLE, 
	"BANK_NM" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "BANK_MST_PK" PRIMARY KEY ("BANK_ID"));
     
    CREATE TABLE "BRANCH_MST"
    (   "BRANCH_ID" CHAR(4 BYTE) NOT NULL ENABLE,
    "BRANCH_NM" VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CONSTRAINT "BRANCH_ID_PK" PRIMARY KEY ("BRANCH_ID"));
   
   CREATE TABLE TRANSACTION_TYPE(
    TRAN_TYPE CHAR(1 BYTE) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(25 BYTE) NOT NULL ENABLE, 
CONSTRAINT TRANSACTION_TYPE_PK PRIMARY KEY (TRAN_TYPE)); 

CREATE TABLE TRANSACTION(	
    TRAN_ID NUMBER(*,0) NOT NULL ENABLE, 
	TRAN_DATE DATE DEFAULT SYSDATE NOT NULL ENABLE,  
    ACCT_ID CHAR(14 BYTE) NOT NULL ENABLE,
    "ACCT_TYPE" CHAR(1 BYTE) NOT NULL ENABLE,
	TRAN_TYPE CHAR(1 BYTE) NOT NULL ENABLE, 
	TRAN_AMOUNT NUMBER(14,2) NOT NULL ENABLE, 
	TOTAL_AMT NUMBER(14,0) NOT NULL ENABLE, 
    "BENEF_ID" NUMBER, 
CONSTRAINT TRANSACTION_PK PRIMARY KEY (TRAN_ID), 
CONSTRAINT TRAN_TYPE_FK FOREIGN KEY (TRAN_TYPE)
REFERENCES TRANSACTION_TYPE (TRAN_TYPE) ENABLE);

    CREATE TABLE "CUST_FACT"
    (   "CUSTOMER_ID" NUMBER NOT NULL ENABLE,
    ACCT_ID CHAR(14 BYTE) NOT NULL ENABLE,
    "ACCT_TYPE" CHAR(1 BYTE) NOT NULL ENABLE,
    "BANK_ID" CHAR(4 BYTE) NOT NULL ENABLE,
    "BRANCH_ID" CHAR(4 BYTE) NOT NULL ENABLE,
    TRAN_ID NUMBER(*,0) NOT NULL ENABLE, 
    "BALANCE" NUMBER(14, 2) NOT NULL ENABLE,
    TRAN_DATETIME DATE DEFAULT SYSDATE NOT NULL ENABLE,  
	TRAN_TYPE CHAR(1 BYTE) NOT NULL ENABLE, 
	TRAN_AMOUNT NUMBER(14,2) NOT NULL ENABLE);



 