
--time source 
CREATE TABLE TIME_INFO AS
SELECT
          DT TDATE,
          TO_CHAR(DT,'DD') DAY,
          TO_CHAR(DT,'MON') MONTH,
          TO_CHAR(DT,'RRRR') YEAR
         FROM (SELECT 
             (TO_DATE('2010-01-01', 'yyyy-mm-dd')) + NUMTODSINTERVAL((LEVEL - 1), 'day') AS DT 
             FROM DUAL 
                 CONNECT BY (LEVEL - 1) <= (ADD_MONTHS(TO_DATE('2010-01-01', 'yyyy-mm-dd'), 20 * 12) - TO_DATE('2010-01-01', 'yyyy-mm-dd') - 1)
              )
              ORDER BY 1 DESC
;


--Query 1
SELECT ACCT_ID,
(CASE WHEN ACCT_TYPE = 'S' THEN 'Saving' 
WHEN ACCT_TYPE = 'C' 
THEN 'Chequing' else '' END) AS ACCT_TYPE, 
MONTH_YEAR, 
ROUND(AVG(BALANCE)) AS AVERAGE_BALANCE
FROM
(
SELECT DISTINCT ACCT_ID, ACCT_TYPE, TRAN_DATETIME, 
TO_CHAR(TRAN_DATETIME,'MON-RRRR') AS MONTH_YEAR, 
TO_CHAR(TRAN_DATETIME,'MON') AS MONTH, 
TO_CHAR(TRAN_DATETIME,'RRRR') AS YEAR, BALANCE
FROM CUST_FACT F ) F JOIN TIME_INFO T 
ON (T.MONTH = F.MONTH AND T.YEAR = F.YEAR 
AND T.YEAR BETWEEN '2017' AND '2021')
GROUP BY ACCT_ID, ACCT_TYPE, MONTH_YEAR
ORDER BY ACCT_ID, ACCT_TYPE, MONTH_YEAR;


--Query 2
SELECT  MONTH_YEAR, COUNT(TRAN_ID) AS TOTAL_TRANSACTIONS, SUM(TRAN_AMOUNT) AS AVERAGE_BALANCE
FROM(
SELECT DISTINCT TRAN_ID, TRAN_DATETIME, TO_CHAR(TRAN_DATETIME,'MON-RRRR') AS MONTH_YEAR, 
TO_CHAR(TRAN_DATETIME,'MON') AS MONTH, TO_CHAR(TRAN_DATETIME,'RRRR') AS YEAR, TRAN_AMOUNT
FROM CUST_FACT F ) F 
JOIN TIME_INFO T ON (T.MONTH = F.MONTH AND T.YEAR = F.YEAR AND T.YEAR BETWEEN '2018' AND '2021')
GROUP BY MONTH_YEAR HAVING COUNT(TRAN_ID) >= 10 AND SUM(TRAN_AMOUNT) > 5000;


--Query 3
SELECT TO_CHAR(A.OPEN_DATE,'RRRR') YEAR, 
COUNT(DISTINCT F.ACCT_ID), 
SUM(CASE F.TRAN_TYPE WHEN '1' 
THEN TRAN_AMOUNT  ELSE 0 END) DEPOSIT,
SUM(CASE F.TRAN_TYPE WHEN '1' 
THEN 0  ELSE TRAN_AMOUNT END) WITHDRAWL
FROM CUST_FACT F JOIN CUSTOMER C
ON (F.CUSTOMER_ID = C.CUSTOMER_ID
AND C.PROVINCE = 'ON')
JOIN ACCOUNT A
ON (F.ACCT_ID = A.ACCT_ID
AND F.ACCT_TYPE = A.ACCT_TYPE)
GROUP BY C.PROVINCE, TO_CHAR(A.OPEN_DATE,'RRRR')
ORDER BY C.PROVINCE, TO_CHAR(A.OPEN_DATE,'RRRR');
